linters:
  enable-all: true
  disable:
  - interfacer
  - maligned
  - scopelint
  - golint
  - forbidigo
  - gomnd
  - gochecknoinits
  - gci
  - depguard
  - exhaustivestruct
  - exhaustive
  - exhaustruct
  - gochecknoglobals
  - godox
  - gofumpt
  # deprecated
  - deadcode
  - varcheck
  - nosnakecase
  - ifshort
  # no generic support
  - structcheck
  - nolintlint

issues:
  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: _test\.go
    linters:
    - dupl
    - errcheck
    - gocyclo
    - paralleltest
    - tparallel
    - goerr113
    - goconst
    - gosec
    - lll
    - varnamelen
