// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCmdInterface is an autogenerated mock type for the CmdInterface type
type MockCmdInterface struct {
	mock.Mock
}

type MockCmdInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmdInterface) EXPECT() *MockCmdInterface_Expecter {
	return &MockCmdInterface_Expecter{mock: &_m.Mock}
}

// CombinedOutput provides a mock function with given fields:
func (_m *MockCmdInterface) CombinedOutput() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCmdInterface_CombinedOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CombinedOutput'
type MockCmdInterface_CombinedOutput_Call struct {
	*mock.Call
}

// CombinedOutput is a helper method to define mock.On call
func (_e *MockCmdInterface_Expecter) CombinedOutput() *MockCmdInterface_CombinedOutput_Call {
	return &MockCmdInterface_CombinedOutput_Call{Call: _e.mock.On("CombinedOutput")}
}

func (_c *MockCmdInterface_CombinedOutput_Call) Run(run func()) *MockCmdInterface_CombinedOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmdInterface_CombinedOutput_Call) Return(_a0 []byte, _a1 error) *MockCmdInterface_CombinedOutput_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCmdInterface_CombinedOutput_Call) RunAndReturn(run func() ([]byte, error)) *MockCmdInterface_CombinedOutput_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCmdInterface creates a new instance of MockCmdInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmdInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmdInterface {
	mock := &MockCmdInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
